from time import sleep

from post_prevency import send_multipart_post
from comment_prevency import send_comment_post


i=0
bearer="Bearer 41201|Lihagh8VOjQqXPZUa6duXOVNwp0BOfBmanaquvRT"
exid="785"
platform = ["profilemag", "bleeper"]


hacker_ids=["20998", "20997", "20999"]
bluestudent_id=["20801","20802","20803","20804","20805", "20818", "20821", "20822", "20823", "20824", "20825"]
messages=[
"I’ve been thinking a lot lately about the importance of mental health and self-care. It’s easy to get caught up in the daily hustle and forget to take time for ourselves. But I’ve learned that it’s absolutely necessary to prioritize your well-being. Whether it’s taking a walk in nature, journaling your thoughts, or simply having a cup of tea in peace, self-care doesn’t have to be complicated. Sometimes it’s the smallest moments that can make the biggest difference. Remember, you can’t pour from an empty cup. 💖",
"I’m feeling so grateful for my friends and family today. I know that not everyone has a strong support system, and I never take it for granted. There’s something really special about having people who will cheer you on, offer a shoulder to lean on, and make you laugh until your stomach hurts. Life can be tough sometimes, but it’s so much easier to navigate when you have people who care about you. I’m sending out lots of love to my inner circle today. Thank you for being there for me, always. 🥰",
"Just finished a huge project at work, and I’m feeling a mix of exhaustion and pride. It’s always such a relief to get something major off my plate, but the process was definitely challenging. I’ve learned so much during the journey, especially about time management, communication, and working through tough moments when you feel like giving up. I think it’s easy to focus on the final result, but I try to remember that the growth happens in the struggle. On to the next challenge! 💼",
"Sometimes it’s hard to appreciate how far you’ve come until you take a step back and reflect. A few years ago, I would have never imagined that I’d be in the place I am now—both personally and professionally. Sure, there were setbacks and moments when I doubted myself, but those were the moments that made me stronger. I used to think success was about getting everything right the first time, but now I realize it’s more about showing up, staying persistent, and learning along the way. Growth is a process, not a destination. 🌱",
"Today was one of those days where everything seemed to go wrong, and I couldn’t help but feel frustrated. I know it’s a part of life—some days are just harder than others—but it doesn’t make it any easier. It’s during these tough moments that I try to remind myself that setbacks are often opportunities in disguise. Sometimes things don’t go the way we want, but that doesn’t mean the universe is against us. It might just be redirecting us to something better. Here’s to tomorrow being a brighter day. 🌟",
"I’ve been reflecting on my journey with health and fitness lately. It’s been a rollercoaster, to say the least. I used to be someone who would start a workout routine, get excited for a week, and then completely burn out. But something shifted in me recently. I stopped focusing on perfection and started focusing on consistency. I’ve realized that it’s not about hitting the gym every day; it’s about finding activities that I enjoy and making small, sustainable changes. It’s been a slow process, but I feel so much better. 💪",
"I had the most amazing weekend getaway! It was a much-needed break from the hustle and bustle of everyday life. There’s something so refreshing about being in nature, breathing in the fresh air, and just disconnecting from technology. We spent the whole weekend hiking, cooking over a campfire, and just soaking in the beauty around us. It’s crazy how a couple of days in the wilderness can help you feel so recharged. I’m already planning my next adventure! If you haven’t spent time in nature lately, I highly recommend it. 🌄",
"Something that’s been on my mind a lot lately is the importance of kindness. We live in a world where it’s easy to get caught up in negativity and stress, but kindness has such a powerful ripple effect. Whether it’s a small compliment, holding the door for someone, or just offering a listening ear, these simple acts can make someone’s day. I’ve been trying to make kindness a priority in my life, not just because it feels good, but because I know it can have a bigger impact than I realize. Let’s spread more kindness today. 💛",
"I’ve been trying to get better at managing my time lately. It’s something I’ve always struggled with, especially when there’s a lot on my plate. But I’ve come to realize that good time management isn’t about working harder or faster; it’s about being intentional with how I spend my time. I’ve started using a planner to break down my day into manageable chunks and it’s been a game-changer. It’s still a work in progress, but I feel more in control of my time, and that makes all the difference. ⏰",
"Have you ever had one of those days where you feel like everything is falling into place? I had one of those days today. Everything just clicked. I was in the zone at work, had meaningful conversations with friends, and even took time to relax and enjoy the little things. It’s funny how you can go through life feeling stressed or distracted, and then out of nowhere, you have a day where everything just feels right. I’m trying to hold onto that feeling and take it with me into the week ahead. ✨",
"Life can feel really overwhelming sometimes, especially when you’re juggling work, family, and everything else. But I’ve learned that it’s okay to not have everything together all the time. There’s no one-size-fits-all formula for balancing it all, and it’s okay to ask for help when you need it. What’s helped me is remembering to prioritize the things that matter most—my health, my relationships, and my happiness. Everything else can wait. We’re all doing the best we can. 💜",
"I’ve been on a mission to find balance in my life. It’s so easy to get caught up in work, social obligations, and the endless to-do list, but I’ve come to realize that balance is key to feeling fulfilled. I’ve started making time for things that bring me joy, whether it’s reading, cooking, or spending time with loved ones. I’m learning that it’s okay to say no to things that drain me, and that self-care is not selfish. Finding balance is a journey, but I’m taking it one day at a time. ⚖️",
"I’ve been doing a lot of self-reflection lately, and it’s honestly been kind of eye-opening. We get so caught up in the fast pace of life that we often forget to check in with ourselves. I’ve been asking myself some hard questions like, ‘Am I truly happy with where I’m at in life?’ and ‘Am I doing things that align with my values?’ It’s been an uncomfortable but necessary process. I think growth comes from being honest with yourself, even when the answers aren’t what you expect. 🌱",
"I had the best experience today volunteering at a local shelter. It’s something I’ve always wanted to do, but I never made the time for it until now. It was humbling to see so many people in need, but it was also inspiring to know that I could make even a small difference in their day. Volunteering really puts things into perspective and reminds me how much I have to be grateful for. I’m going to make it a point to give back more often. If you’re able to, I highly recommend volunteering. ❤️",
"I’m feeling incredibly blessed today. It’s not often that I take the time to sit down and really reflect on all the good things in my life, but today I did. Sometimes we get so focused on what’s going wrong that we forget to appreciate what’s going right. I’ve got a loving family, amazing friends, a roof over my head, and good health. I think it’s important to pause and acknowledge the blessings, big and small. Life is precious, and I’m so grateful for everything I have. 🙏",
"I’ve been thinking about my goals a lot lately. It’s easy to get discouraged when things don’t seem to be moving as quickly as we’d like. But I’m learning that progress is progress, no matter how small. Every step forward is a step in the right direction. I’ve also realized that it’s important to celebrate the small wins. Whether it’s completing a task or having a productive day, those little victories add up. So here’s to staying patient and trusting the process. ✨",
"Some days, I just need to slow down and breathe. Life can get so hectic, and I often find myself rushing from one thing to the next, without taking a moment to appreciate the present. Today, I decided to take a break. I spent a few minutes outside, closed my eyes, and just focused on my breath. It was surprisingly calming. I’m going to try to make this a daily practice—taking a few minutes to check in with myself and reset my mind. It’s such a simple thing, but it makes a world of difference. 🌿",
"Has anyone else noticed how much of a difference a good night’s sleep makes? I used to think I could function on a few hours of sleep, but I’ve learned that’s not the case. Lately, I’ve been prioritizing my rest, and I can honestly say I feel so much better. I’m more productive, more focused, and just in a better mood overall. Sleep is so underrated, but it’s one of the best things we can do for ourselves. If you’re not getting enough sleep, do yourself a favor and try to get some extra rest tonight. 💤",
"Today, I took a moment to reflect on the things that truly matter to me. It’s so easy to get distracted by the noise of social media, work, and other obligations, but I’ve been making a conscious effort to focus on what really brings me peace and joy. For me, that’s my family, my health, and doing work that feels meaningful. I’m trying to spend less time worrying about things that don’t matter and more time on the things that bring me happiness. It’s a work in progress, but I’m getting there. 💫",
"Just got back from a yoga class and I feel incredible! It’s amazing how just an hour of stretching and focusing on my breath can do wonders for my body and mind. Yoga is something I’ve been meaning to try for years, and I’m so glad I finally did. It’s not just a workout; it’s a way to reconnect with yourself and clear your mind. I’m definitely going to make it a regular part of my routine. If you’ve never tried yoga, I highly recommend it. It’s truly life-changing. 🧘‍♀️",
]

#send_multipart_post(bearer=bearer,userid="20826" ,message=messages[2], exid=exid)

# send_comment_post(post_id, comment_author, comment_text, exid=exid)

for message in messages:
    send_multipart_post(bearer=bearer,userid=bluestudent_id[i],message=message, exid=exid, platform="profilemag")
    i=i+1
    if i >= len(bluestudent_id):
        i = 0

    sleep(12)
